# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.gyandeeps.com
title: Gyandeep Singh
email: gyandeeps@gmail.com
author: Gyandeep Singh
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

excerpt_separator: <!--more-->  
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/gyandeeps
  - title: github
    url: https://github.com/gyandeeps
  - title: linkedin
    url: https://www.linkedin.com/in/gyandeeps
